'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class NorthwindEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NorthwindEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Customers() As DbSet(Of Customer)

    Public Overridable Function CustOrderHist(customerID As String) As ObjectResult(Of CustOrderHist_Result)
        Dim customerIDParameter As ObjectParameter = If(customerID IsNot Nothing, New ObjectParameter("CustomerID", customerID), New ObjectParameter("CustomerID", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of CustOrderHist_Result)("CustOrderHist", customerIDParameter)
    End Function

End Class
